src/main/java/com/box/sdk/BoxAPIConnection.java, src/main/java/com/box/sdk/BoxAPIConnectionListener.java
The BoxAPIConnection object now supports BoxAPIConnectionListeners which
enable the listener to listen to refresh event
=> Added a listener to BoxAPIConnection

src/main/java/com/box/sdk/BoxAPIConnection.java
The BoxAPIConnection now has a new constructor that allows the user
to create an empty API connection object and authenticate later.
=> BoxAPIConnection made dependency-injection friendly

src/main/java/com/box/sdk/BoxEvent.java, src/test/java/com/box/sdk/BoxEventTest.java
The UNKNOWN event type is used in cases where the API returns a new type
that the SDK doesn't understand. This prevents an exception from being
thrown while parsing the event JSON.
Fixes #50.
=> Add UNKNOWN event type

src/main/java/com/box/sdk/LRUCache.java, src/test/java/com/box/sdk/LRUCacheTest.java
Relying on remove to check if an item is already in the ```LinkedHashSet``` doesn't work because we can get events more than just twice.  The first time an ID is added this will work, and the second time the ID is added this will also work, but the third time will fail because we just removed the ID from the hashset in attempt number 2, so the listener gets called every other time.
Fixes #57
=> Always re-add event id to cache after removing

src/main/java/com/box/sdk/BoxAPIConnection.java, src/main/java/com/box/sdk/BoxFolder.java
The SDK has partial support for custom domains using getBaseURL/setBaseURL and getBaseUploadURL/setBaseUploadURL.
There were two missing pieces though:
First, the SDK also required getTokenURL/setTokenURL to use a custom domain token endpoint.
Second, the BoxFolder class did not use BoxAPIConnection.getBaseUploadURL, so uploads would not work.
This commit fixes those two issues.
=> Fixed custom domain support

.gitignore, src/main/java/com/box/sdk/Metadata.java, src/test/java/com/box/sdk/BoxFileTest.java, src/test/java/com/box/sdk/MetadataTest.java
Now using the "/path" format for all operations, including get().
Handling missing values more gracefully, returning null.
Fixed bug in integration tests.
Added a bunch of unit tests to catch key vs. path problems.
=> Fixes #67, Fixes #68, Fixes #69 - Metadata feedback and fixes

build.gradle, src/main/java/com/box/sdk/BoxAPIRequest.java, src/main/java/com/box/sdk/BoxAPIResponse.java, src/main/java/com/box/sdk/BoxCollaboration.java, src/main/java/com/box/sdk/BoxCollaborator.java, src/main/java/com/box/sdk/BoxComment.java, src/main/java/com/box/sdk/BoxDateFormat.java, src/main/java/com/box/sdk/BoxEvent.java, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFileVersion.java, src/main/java/com/box/sdk/BoxFolder.java, src/main/java/com/box/sdk/BoxItem.java, src/main/java/com/box/sdk/BoxJSONResponse.java, src/main/java/com/box/sdk/BoxMultipartRequest.java, src/main/java/com/box/sdk/BoxResource.java, src/main/java/com/box/sdk/BoxSharedLink.java, src/main/java/com/box/sdk/BoxUploadEmail.java, src/main/java/com/box/sdk/BoxUser.java, src/main/java/com/box/sdk/StandardCharsets.java, src/test/java/com/box/sdk/BoxCommentTest.java, src/test/java/com/box/sdk/BoxFileTest.java, src/test/java/com/box/sdk/BoxFolderTest.java, src/test/java/com/box/sdk/BoxTrashTest.java
Per customer request, adding backwards support for Java 1.6.
There should be zero functional changes.
Summary of changes:
* Converted "switch on string" to if/else chains.  There may be a slight performance penalty, but it should be negligible compared to the overall HTTPS request.
* Replaced System.lineSeparator() with System.getProperty("line.separator")
* Replaced SimpleDateFormat "X" with "Z"
* Added extra support for ISO 8601 formatted date/time strings
* Replaced StandardCharsets with custom helper class
* Replaced Files.readAllBytes with custom helper method
Fixes #62 - correctly parsing user phone field
=> Adding support for JDK 1.6

src/main/java/com/box/sdk/EventListener.java, src/main/java/com/box/sdk/EventStream.java, src/test/java/com/box/sdk/EventStreamTest.java
If we want to be able to start and stop the ALF stream more granularly, we need to know the last stream position that has already been checked.  There is already a way to start an ALF stream at a specific point, but getting the next_stream_position from the request wasn't there.
=> Added event listener for stream position changes

src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFileVersion.java, src/main/java/com/box/sdk/BoxItem.java, src/test/java/com/box/sdk/BoxFileTest.java
Previously it was not possible to retrieve the "version ID" of a
file.  Version ID is being promoted to a first class primitive.
This commit adds the ability to optionally retrieve the version ID.
=> Adds BoxFile.Info.getVersion()

src/main/java/com/box/sdk/BoxAPIConnection.java, src/test/java/com/box/sdk/BoxAPIConnectionTest.java
The `needsRefresh()` method in `BoxAPIConnection` would always return
false if the expires timestamp is 0. A more intuitive behavior is to
always refresh if we don't know when the token is going to expire. This
avoids issues with constructing an API connection and forgetting to call
`setExpires(long)`. For example:
BoxAPIConnection api = new BoxAPIConnection("id", "secret",
"storedAccess", "storedRefresh");
// This call can fail if the stored access token had expired because
// the expiration timestamp is 0.
BoxFolder rootFolder = BoxFolder.getRootFolder(api);
=> Refresh access token when expires timestamp is 0

src/main/java/com/box/sdk/BoxAPIRequest.java
This allows request interceptors to inspect the body of a request before
it's sent.
=> Add getBody() method of BoxAPIRequest

src/main/java/com/box/sdk/BoxUser.java, src/test/java/com/box/sdk/BoxUserTest.java
Add a `delete()` method to `BoxUser` that allows administrators to
delete users from their enterprise.
=> Delete enterprise user

src/main/java/com/box/sdk/BoxUser.java
This change adds a `deleteEmailAlias()` method to `BoxUser` that removes
an email alias from their account.
=> Delete email alias for a user

src/main/java/com/box/sdk/BoxAPIConnection.java
The authentication calls didn't have the userAgent being sent resulting the default ```Java/1.7.0_uXX``` user agent
=> Add User-Agent headers to the auth requests

src/main/java/com/box/sdk/BoxFile.java
If a download request gets terminated, or errors the request continues to listen to the input stream since the disconnect isn't called in the exception scenario.  I moved the disconnect in a finally block to make sure that it will be called immediately and not leave the network up and running.
=> Long download requests

src/main/java/com/box/sdk/BoxUser.java, src/main/java/com/box/sdk/BoxUserIterator.java, src/test/java/com/box/sdk/BoxUserTest.java
Any comments would be highly appreciated (especially on wording).
=> Closes #94 Get all users in an enterprise.

src/main/java/com/box/sdk/BoxEvent.java, src/main/java/com/box/sdk/EventLog.java, src/test/java/com/box/sdk/EventLogTest.java
The EventLog class provides methods for retrieving static logs of
events. Unlike the EventStream, an EventLog isn't updated in real-time.
For now it only provides a way of retrieving enterprise events, since
those aren't available in real-time via EventStream.
It's also worth noting that there's a bug in the Box events endpoint
where some enterprise event sources don't map correctly to a
BoxResource. In the cases where this happens, the `getSourceInfo()` will
return null, and a new a `getSourceJSON()` method can be used to access
the event source JSON directly.
Closes #81.
=> Add EventLog for retrieving a static log of events

src/main/java/com/box/sdk/BoxAPIConnection.java, src/main/java/com/box/sdk/BoxAPIConnectionListener.java, src/test/java/com/box/sdk/BoxAPIConnectionTest.java
This change adds a `save()` method and a static `restore(String)` method
to BoxAPIConnection. These methods are meant to simplify the process of
saving the state of a connection and then restoring it at a later time.
The `save()` method serializes the state of BoxAPIConnection to a JSON
string which can persisted. The `restore(String)` method takes a JSON
string and reconstructs a BoxAPIConnection using the saved state.
BoxAPIConnectionListener has also had an
`onError(BoxAPIConnection, BoxAPIException)` callback added so that
connection errors can be more easily handled. The `onRefresh()` method
also now receives a BoxAPIConnection object that can be used to save the
newly updated state of the connection.
Closes #104 and fixes #82.
=> Improve saving and restoring BoxAPIConnections

src/main/java/com/box/sdk/BoxGroup.java, src/main/java/com/box/sdk/BoxGroupMembership.java, src/main/java/com/box/sdk/BoxUser.java, src/test/java/com/box/sdk/BoxGroupMembershipTest.java, src/test/java/com/box/sdk/BoxGroupTest.java, src/test/java/com/box/sdk/BoxUserTest.java
=> Add membership related features

src/main/java/com/box/sdk/BoxItem.java, src/test/java/com/box/sdk/BoxFolderTest.java
When getting info about a folder, its `path_collection` field should be
parsed as a collection of BoxFolder.Info instead of BoxFolder. This way
additional fields (such as the folder's name) can be returned.
Fixes #105.
=> Parse path collections as BoxFolder.Info

src/main/java/com/box/sdk/BoxAPIConnection.java, src/test/java/com/box/sdk/BoxAPIConnectionTest.java
This change removes the client ID and client secret parameters from the
JSON state blob for BoxAPIConnections. It generally isn't a good
security practice to store your client ID and secret along with
access/refresh tokens, so the restore method was changed to take them as
separate parameters which need to be provided by the application.
There is also a new non-static `restore(String)` method that allows for
a connection state to be restored into an existing connection. This
method helps in situations where the saved state isn't immediately
available when the API connection is constructed.
=> Remove client ID and secret from connection state

src/main/java/com/box/sdk/BoxAPIResponse.java
Since every request has a header "Accept-Encoding: gzip", the server error response can be gzip compressed and needs to be inflated.
Easiest way to reproduce:
new BoxFile(api, "0").getInfo("type");
throws BoxAPIException with code 404 and with gzip compressed response string.
=> Handle gzip encoded error response

src/main/java/com/box/sdk/BoxCollaboration.java, src/main/java/com/box/sdk/BoxFolder.java, src/test/java/com/box/sdk/BoxFolderTest.java
Since the "group" type wasn't being handled when creating a new
collaboration, an IllegalArgumentException would be thrown. This fix
handles group types correctly and will successfully create group-based
collaborations.
When retreiving collaborations, the JSON was parsed as a list of users
instead of a list of users or groups. This led to BoxUser.Info objects
being returned with incorrect or unpopulated fields. This fix makes it
so the "type" field is checked for each item in the list, and the JSON
gets parsed into its appropriate type.
Fixes #116.
=> Handle groups when retrieving and creating collabs

src/main/java/com/box/sdk/BoxEvent.java, src/test/java/com/box/sdk/BoxEventTest.java
Add getters for the "created_at", "created_by", and "session_id" fields.
There are also getters added for some undocumented fields that may show
up in enterprise events. These fields are "ip_address",
"additional_details", and "accessible_by".
The "additional_details" field doesn't have a known schema, so it has to
be exposed as a raw `JsonObject` (similar to what had to be done for the
"source" field). This may no longer be necessary once the bugs in the
enterprise events stream are fixed.
=> Add some additional fields to BoxEvent

src/main/java/com/box/sdk/BoxAPIConnection.java, src/main/java/com/box/sdk/BoxAPIRequest.java, src/main/java/com/box/sdk/SharedLinkAPIConnection.java
This change introduces an access token read lock that can be used to
prevent the access token from being refreshed before a request is sent.
When calling `BoxAPIConnection.getAccessToken()`, the access token is
only locked until it is read and returned. This means that a request can
be sent with an invalid access token if a refresh occurred between the
time when `getAccessToken()` was called and the request was sent.
The new `lockAccessToken()` and `unlockAccessToken()` methods allow for
requests to keep the token locked until they're finished being sent.
These methods are package-private for now, since their misuse can easily
cause deadlocks.
=> Fix OAuth race condition when refreshing

src/main/java/com/box/sdk/BoxAPIConnection.java
Configured proxies aren't saved or restored with
BoxAPIConnection#save() or BoxAPIConnection#restore(String). This is
intentional because:
1. We don't have a clean way of serializing the Proxy object to JSON.
2. If the proxy has a password, it would be unsafe to persist it to the
saved state string.
This change updates the javadocs so it's clear that proxy settings must
be manually reconfigured after restoring an API connection.
Fixes #143.
=> Update docs around saving/restoring proxy settings

README.md, build.gradle, src/example/java/com/box/sdk/example/AccessAsAppUser.java, src/example/java/com/box/sdk/example/CreateAppUser.java, src/main/java/com/box/sdk/BoxAPIConnection.java, src/main/java/com/box/sdk/BoxDeveloperEditionAPIConnection.java, src/main/java/com/box/sdk/JWTEncryptionPreferences.java, src/test/java/com/box/sdk/BoxAPIConnectionTest.java
The coding style check was not allowing to add another parameter by hitting the limit of 7 parameters. Hence separated all JWT encryption preferences into a separate param class for easy passing around.
=> App User Key Id support and version update.

src/main/java/com/box/sdk/EventLog.java
Fix to avoid StringIndexOutOfBounds exception when position is non-zero and event types array is empty.
=> Added length check on event types array. Closes #187

src/main/java/com/box/sdk/BoxFile.java
removed expiring_embed_link from ALL_FIELDS. Not all file types support preview yet and this is also not a field that should just casually be returned as "info"
=> fixes issue #196

src/main/java/com/box/sdk/BoxCollaboration.java
getInfo() should be making a call to /collaborations/{id} if it's
retrieving information about a collaboration. Old method was making a
call to /collaborations resulting in a 400 error as the endpoint
/collaborations does not accept a GET without a collaboration id or
?status=pending
=> Fix collaboration getInfo() method. Closes #204.

build.gradle, src/main/java/com/box/sdk/BoxAPIConnection.java, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/Metadata.java
Fixes issue #179
Added support for specifying the scope parameter when performing metadata operations.  This is required to access any custom metadata types.
=> Fix metadata

src/main/java/com/box/sdk/BoxMultipartRequest.java, src/test/java/com/box/sdk/BoxMultipartRequestTest.java
This is in accordance with Box API recommendation.
From https://box-content.readme.io/reference#upload-a-file:
"Note that the file bytes should come after the JSON for best
performance."
=> Issue #225: Send file bytes after JSON

src/main/java/com/box/sdk/EventLog.java, src/test/java/com/box/sdk/EventLogTest.java
Fixed #131 & #198 , by removing the date after and before from ENTERPRISE_EVENT_URL_TEMPLATE and added to queryBuilder.
This way the '+' sign in the timezone will get URLencoded properly.
Fixed the errors.
=> Timezone issue

config/checkstyle/checkstyle.xml, src/main/java/com/box/sdk/BoxDateFormat.java, src/main/java/com/box/sdk/BoxFolder.java, src/main/java/com/box/sdk/BoxSearchParameters.java, src/test/java/com/box/sdk/BoxFolderTest.java, src/test/java/com/box/sdk/BoxSearchParametersTest.java, src/test/java/com/box/sdk/BoxSearchTest.java, src/test/java/com/box/sdk/BoxTaskTest.java
Adding unit tests for search functionality (Decided against any integration tests due to the search indexing delay). 
Removed the `keyword` param which, as far as I can tell, is not valid.
Added a check to ensure either a `query` or a `metadata filter` is provided when searching.
Converted `BoxDateFormatter` to use UCT time
@codyebberson @gcurtis @rschaller-box
=> Search tests and fixes

config/checkstyle/checkstyle.xml
RedundantThrows was removed with version 6.2 (see https://github.com/checkstyle/checkstyle/issues/473)
=> Removing Redundant Throws from CheckStyle

src/main/java/com/box/sdk/QueryStringBuilder.java, src/test/java/com/box/sdk/BoxSearchParametersTest.java, src/test/java/com/box/sdk/BoxSearchTest.java
Modifying `QueryStringBuilder` to the `URLEncoder` class
=> Use URLEncoder class for encoding query params

src/main/java/com/box/sdk/BoxFile.java
Added BoxFile metadata overrides for non-standard metadata scope.
Metadata templates can be "global" or "enterprise".  The SDK's initial metadata implementation assumed that the default template was "global", and that all other templates are "enterprise".  That assumption is not valid (although does cover most common cases).
I added the equivalent override for getMetadata() in a previous commit.  Now adding support for createMetadata() and deleteMetadata().  The updataMetadata() method does not need an override, because it pulls scope from the Metadata parameter.
=> Added metadata scope overrides

src/main/java/com/box/sdk/BoxMetadataFilter.java
Template keys are case sensitive, we should not be converting them to lower case when adding them to the search.
=> Fix metadata filter methods (Closes #296)

src/main/java/com/box/sdk/BoxCollaboration.java
When you give away ownership with the pattern:
```
BoxCollaboration.Info newCollaborationInfo = folder.collaborate(userName, BoxCollaboration.Role.EDITOR);
newCollaborationInfo.setRole(BoxCollaboration.Role.OWNER);
BoxCollaboration bc = newCollaborationInfo.getResource();
bc.updateInfo(newCollaborationInfo);
```
It throws a ClassCastException because BoxCollaboration.java is expecting BoxJSONResponse. But, giving away ownership is a BoxAPIResponse because the content returned is:
```
PUT https://api.box.com/2.0/collaborations/123456789
HTTP/1.1 204 No Content
Age: 0
Date: Tue, 16 Feb 2016 21:45:50 GMT
Content-Length: 0
Connection: keep-alive
Server: ATS
Cache-Control: no-cache, no-storenull
```
While this patch handles the ClassCastException, it does nothing to update the `info` argument, …
=> Fix ClassCastException when giving away ownership. Closes #147

src/main/java/com/box/sdk/BoxGroup.java, src/main/java/com/box/sdk/BoxGroupMembershipIterator.java
This method wasn't correctly paginating results and only returned the first 100 memberships. This change returns all of them by automatically paging.
Ideally, we'd like to return an Iterator that allows for lazy paging, but that would require a method signature change. This is tracked as a breaking change in #335.
This change was originally authored by Dor Fire, but modified to prevent the backwards-incompatible change.
Fixes #316.
=> Return all results for BoxGroup.getMemberships()

src/main/java/com/box/sdk/BoxTaskAssignment.java
Wrong URLTemplate of BoxTaskAssignment value altered to match API reference.
BoxTaskAssignment.update method signature was altered to accept BoxTaskAssignment.Info object as a param instead of BoxTask.Info. So that change can cause some compatibility issues, if any third party code uses that method with wrong signature.
=> Fix for BoxTaskAssignment

README.md, doc/retention_policies.md, src/main/java/com/box/sdk/BoxResource.java, src/main/java/com/box/sdk/BoxRetentionPolicy.java, src/main/java/com/box/sdk/BoxRetentionPolicyAssignment.java, src/test/java/com/box/sdk/BoxRetentionPolicyAssignmentTest.java, src/test/java/com/box/sdk/BoxRetentionPolicyTest.java
Create Retention Policy Assignment implemented as assignTo(..) and assignToEnterprise(..) methods of BoxRetentionPolicy object.
Get Retention Policy Assignment implemented as getInfo(..) method of BoxRetentionPolicyAssignment method.
Get Retention Policy Assignments features implemented as getFolderAssignments(..), getEnterpriceAssignments(..) and getAllAssignments(..) methods of BoxRetentionPolicy object.
Methods are covered with unit tests and documented.
Pull request contains code from [Retention Policies basic features](https://github.com/box/box-java-sdk/pull/317)
=> Retention Policy assignments

README.md, doc/watermarking.md, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFolder.java, src/main/java/com/box/sdk/BoxItem.java, src/main/java/com/box/sdk/BoxWatermark.java, src/test/java/com/box/sdk/BoxFileTest.java, src/test/java/com/box/sdk/BoxFolderTest.java
Watermarking features implemented for BoxFile and BoxFolder with unit tests and markdown documentation.
=> Watermarking features

src/main/java/com/box/sdk/BoxFileVersion.java, src/test/java/com/box/sdk/BoxFileVersionTest.java
BoxFileVersion object refactored:
- provided opportunity to set associated file's id not only thru constructor;
-  API response json object, obtained thru promote() call, now parsed to update fields of the object;
Unit tests were added for Delete Old Version and Promote Version (delete() and promote() methods)
=> Fixed and tests for Delete and Promote File Version

src/main/java/com/box/sdk/BoxResource.java
Added the BoxWebLink to the RESOURCE_CLASS_BY_TYPE map so web_link related BoxEvents can be successfully deserialised and won't have null sourceInfo.
Closes #413
=> Allow deserialisation of BoxEvents for WebLinks (413 fix)

src/main/java/com/box/sdk/BoxAPIRequest.java, src/main/java/com/box/sdk/BoxGlobalSettings.java, src/main/java/com/box/sdk/RealtimeServerConnection.java
Currently there is no easy way to set the socket timeout's for the Http url connection, since the attributes are on the BoxAPIRequest and BoxAPIRequest's are created in many places internally.
=> Ability to set connect and read timeout globally.

src/main/java/com/box/sdk/BatchAPIRequest.java, src/main/java/com/box/sdk/BoxJSONRequest.java, src/test/java/com/box/sdk/BatchAPIRequestTest.java, src/test/java/com/box/sdk/MetadataTemplateTest.java
Loosen internal restrictions in BoxJSONRequest to allow for JSON
types other than objects, since metadata template updates use a
JSON array as the top level body.
Fixes #489
=> Fix MetadataTemplate.updateMetadataTemplate() type error

src/main/java/com/box/sdk/BoxUser.java
Summary: please comment out line 407 of the BoxUser.java class in the SDK and attempt again:
response.disconnect();
Explanation: Line 405 of BoxUser.java, which is inside BoxUser.moveFolderToUser(), includes this call:
JsonObject responseJSON = JsonObject.readFrom(response.getJSON());
response.jgetJSON() is defined in the class BoxJSONResponse.java.
```    /**
* Gets the body of the response as a JSON string. When this method is called, the response's body will be read and
* the response will be disconnected, meaning that the stream returned by {@link #getBody} can no longer be used.
* @return the body of the response as a JSON string.
*/
public String getJSON() {
if (this.json != null) {
return this.json;
}
InputStreamReader reader = new InputStreamReader(this.getBody(), …
```
=> Delete redundant response.disconnect() from moveFolderToUser()

src/test/java/com/box/sdk/BoxAPIRequestTest.java, src/test/java/com/box/sdk/BoxCollectionTest.java, src/test/java/com/box/sdk/BoxFolderTest.java, src/test/java/com/box/sdk/BoxGroupMembershipTest.java, src/test/java/com/box/sdk/BoxGroupTest.java, src/test/java/com/box/sdk/BoxSearchTest.java, src/test/java/com/box/sdk/BoxUserTest.java, src/test/java/com/box/sdk/EventStreamTest.java, src/test/java/com/box/sdk/MetadataTemplateTest.java
Changes wiremock in tests to use a private port instead of 8080, which is popular with web servers.
Fixes #60
=> Change wiremock port

src/main/java/com/box/sdk/BoxFolder.java, src/main/java/com/box/sdk/FileUploadParams.java, src/test/java/com/box/sdk/BoxFolderTest.java
Added a sha1 attribute to FileUploadParams to enable sending the
expected hash of the file for verification that the file was not
corrupted in transit.
Fixes #328
=> Add option to pass file SHA-1 hash for upload integrity

build.gradle, src/main/java/com/box/sdk/BoxAPIException.java, src/main/java/com/box/sdk/BoxAPIResponse.java, src/main/java/com/box/sdk/BoxDeveloperEditionAPIConnection.java, src/main/java/com/box/sdk/EventStream.java, src/test/java/com/box/sdk/BoxDeveloperEditionAPIConnectionTest.java, src/test/java/com/box/sdk/BoxFolderTest.java, src/test/java/com/box/sdk/BoxGroupTest.java, src/test/java/com/box/sdk/BoxSearchTest.java, src/test/java/com/box/sdk/EventStreamTest.java
If JWT auth fails, attempt a manual retry that:
1. Regenerates the `jti` claim to avoid scenarios where the JWT ID was already consumed
2. Uses the Date header from the API response to calculate the JWT `exp` claim, to avoid issues related to clock drift
Fixes #519
Fixes #475
=> Perform modified retry on JWT auth

src/main/java/com/box/sdk/BoxFile.java, src/test/java/com/box/sdk/BoxFileTest.java
Add a new BoxFile#uploadNewVersion() method that returns the
BoxFile.Info from the API response, and deprecate the old
BoxFile#uploadVersion() method that returns void.
Fixes #518
=> Add updated file version upload endpoint

doc/files.md, doc/legal_holds.md, doc/metadata_template.md, doc/retention_policies.md, doc/tasks.md, doc/terms_of_service.md, doc/users.md, doc/webhooks.md
Fixing some broken Javadoc links, formatting issues, etc.
=> Fix more documentation issues

README.md, doc/collaborations.md, doc/files.md, doc/groups.md, doc/recent_items.md, doc/tasks.md, doc/trash.md, doc/webhooks.md, src/test/java/com/box/sdk/BoxCollaborationTest.java
A review of our documentation identified 14 endpoints that are fully implemented but not yet documented.  Added documentation for these to help users find these endpoints and understand how to use them in the SDK.
=> Add missing documentation for undocumented endpoints

src/main/java/com/box/sdk/LargeFileUpload.java
Issue 541 - Out of Memory exceptions due to back log of queued items in the ThreadPoolExecutor
Resolution:
Added Queue Size Handling For ThreadPoolExecutor in LargeFileUpload.uploadParts().  This consisted of a line to determine the Max Queue Size, which was set to 1.5 times the max number of worker threads.  Then adding a check to see if the queue is less than that Max size, before reading in the next set of bytes and adding another task to the queue.
=> ISSUE #541 Large File Upload Memory

README.md, build.gradle
Because of our dependency on jose4j, the SDK requires at least
Java 7 in order to run.  To clarify this, updating build.gradle
with the correct minimum version and adding a note to the README.
Fixes #482
=> Clarify required Java version

src/main/java/com/box/sdk/BoxCollaboration.java, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFolder.java, src/test/java/com/box/sdk/BoxFileTest.java, src/test/java/com/box/sdk/BoxFolderTest.java
Fixed a bug where the `notify` parameter when creating a collab
was placed in a header instead of the query string.
Also did some opportunistic refactoring to consolidate collab
creation API call logic in one place in the BoxCollaboration
class to avoid duplicate code.
Fixes #544
=> Fix collaboration notify parameter

src/main/java/com/box/sdk/EventStream.java, src/test/java/com/box/sdk/EventStreamTest.java
Inserting a delay between polling calls to get more events in order to control the number of API calls made by the Event Stream.  Because there may be duplicates in the stream, it is currently possible for the stream to make 3-5 calls per second even in cases when the user sees no new events — this is obviously undesirable.  The default is now to wait 1s between calls, and is user-configurable.
=> Delay successive API calls by EventStream

src/main/java/com/box/sdk/BoxAPIRequest.java, src/test/java/com/box/sdk/BoxAPIRequestTest.java
The Box API will be deprecating TLSv1.0 support in the future, but
Java 7 environments use that protocol by default.  The SDK needs
to force TLSv1.1 or greater to maintain compatibility with the Box
API.  This should work in all supported Java versions (7+).
=> Force TLSv1.1 or greater when supported

src/main/java/com/box/sdk/BoxDeveloperEditionAPIConnection.java, src/test/java/com/box/sdk/BoxDeveloperEditionAPIConnectionTest.java
Setting the JWT expiration interval to the maximum allowed time of
60 seconds is not advisable, since the Box API server will actually
reject a JWT assertion if the exp claim is too far in the future.
Clock drift between the SDK and API of even a few seconds could
then cause the JWT to be rejected.  Setting the expiration
interval to 30 seconds instead should maximum the amount of clock
drift allowable before a JWT would get rejected, reducing the
chances of an error.
=> Adjust JWT expiration interval

src/main/java/com/box/sdk/BoxConfig.java
In one of the contructor of BoxConfig class, privateKey was being set on place of privateKeyPassword due to typo.
=> fixed BoxConfig constructor method where privateKeyPassword was not set

src/main/java/com/box/sdk/BoxAPIRequest.java, src/test/java/com/box/sdk/BoxAPIConnectionTest.java
Small fix to prevent BoxAPIRequest#toString() from throwing a null
pointer exception inside of a request interceptor.  Ideally, the
request headers would always be available on the request object
instead of being partially stored on the connection, but in lieu
of that more involved fix, this should restore at least some
functionality in the meantime.
Fixes #133 (at least partially)
=> Quick fix for NPE on request.toString() in interceptor

doc/search.md
- Typo fix: `BoxItems.Info` -> `BoxItem.Info`
Fixes typo
=> Update the file `search.md`

src/main/java/com/box/sdk/BoxAPIConnection.java, src/main/java/com/box/sdk/BoxAPIRequest.java, src/test/java/com/box/sdk/BoxAPIConnectionTest.java
=> Allow per-connection timeouts

doc/authentication.md, doc/collaboration_whitelists.md, doc/collaborations.md, doc/collections.md, doc/comments.md, doc/devices.md, doc/events.md, doc/files.md, doc/folders.md, doc/groups.md, doc/legal_holds.md, doc/metadata_template.md, doc/recent_items.md, doc/retention_policies.md, doc/search.md, doc/shared-items.md, doc/storage_policy.md, doc/tasks.md, doc/terms_of_service.md, doc/trash.md, doc/users.md, doc/watermarking.md, doc/webhooks.md, doc/weblinks.md
I've tagged the majority of code samples to an endpoint for usage in the new developer documentation.
=> Tag code samples for usage in developer docs

src/main/java/com/box/sdk/BoxFolder.java
Sets whether or not the non-owners can invite collaborators to the folder.
=> create set method for CanNonOwnerInvite

.travis.yml
Travis CI is migrating from Ubuntu Trusty to Ubuntu Xenial - however, Xenial does not have support for oracle jdk 8, thus two/three of our builds are failing on the install stage. To fix this issue we need to add the target Trusty to our yaml file in order to stop our installs from defaulting to Xenial.
More context here:
1. https://travis-ci.community/t/install-of-oracle-jdk8-is-failing/4365
2. https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/3
=> Added ubuntu trusty routing over ubuntu xenial to fix issue installing oraclejdk8 with Travis CI

doc/files.md, doc/folders.md, src/main/java/com/box/sdk/Metadata.java, src/test/java/com/box/sdk/MetadataTest.java
Multiselect was missing the functionality to perform a `replace` on it. Added the ability to replace as well as documentation for adding and replacing.
=> Add replace functionality for multi select metadata as well as documentation.

doc/authentication.md
BoxConfig.readFrom() is a convenience function that helps the users create an BoxConfig object. However, this method is not currently documented, just used in examples.
=> Improving authentication docs for BoxConfig.readFrom()

src/main/java/com/box/sdk/BoxTask.java, src/test/Fixtures/BoxTask/CreateATaskWithActionComplete200.json, src/test/java/com/box/sdk/BoxTaskTest.java
Previously, BoxTask was missing the "complete" enum option for allowable actions.
=> Added enum for complete field on BoxTasks Actions enum

CHANGELOG.md, doc/users.md, src/main/java/com/box/sdk/BoxResourceIterable.java, src/main/java/com/box/sdk/BoxUser.java, src/test/Fixtures/BoxUser/GetAllEnterpriseUsersMarkerPagination200.json, src/test/java/com/box/sdk/BoxFileVersionRetentionTest.java, src/test/java/com/box/sdk/BoxUserTest.java
- https://jira.inside-box.net/browse/SDK-1213
- Add marker based pagination for get users methods
- Added usemarker and marker parameters to multiple get users methods
- Updated BoxResourceIterable to be able to pass in marker to start pagination
- Updated BoxResourceIterable to expose the next marker string
- Unit testing
- Manual testing
=> Add marker based pagination for get users methods

doc/folders.md
`Get a Folder's Items` section contains the `getChildren` example where foreach is not applicable to type 'java.util.Iterator'.
=> Get a Folder's Items - getChildren example fix

CHANGELOG.md, doc/metadata_template.md, src/main/java/com/box/sdk/BoxMetadataQueryItem.java, src/main/java/com/box/sdk/MetadataTemplate.java, src/test/Fixtures/BoxMetadataTemplate/MetadataQuery1stResponse200.json, src/test/java/com/box/sdk/BoxFileTest.java
`MetadataTemplate.executeMetadataQuery()` would returned `BoxItem` that did not include the metadata for each item. Now, instead of returning a `BoxItem`, the method returns a `BoxMetadataQueryItem`. This will contain an item and its associated metadata.
=> Return metadata for each item returned by a metadata query

CHANGELOG.md, src/main/java/com/box/sdk/BoxFolder.java, src/test/java/com/box/sdk/BoxFileTest.java, src/test/java/com/box/sdk/BoxFolderTest.java
When large files are uploaded to the chunked upload endpoint using the `Folder.uploadLargeFile()` method, they can fail because of 409 conflict errors. To avoid these errors, we do a preflight check before uploading. The preflight check will determine whether the file is already uploaded rather than uploading the file, then finding that out. This will reduce network traffic.
=> Add preflight check before chunked uploads

CHANGELOG.md, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFileVersion.java, src/main/java/com/box/sdk/BoxFolder.java, src/main/java/com/box/sdk/BoxMetadataCascadePolicy.java, src/main/java/com/box/sdk/BoxStoragePolicyAssignment.java, src/main/java/com/box/sdk/EventStream.java, src/main/java/com/box/sdk/MetadataTemplate.java, src/main/java/com/box/sdk/URLTemplate.java, src/test/java/com/box/sdk/BatchAPIRequestTest.java, src/test/java/com/box/sdk/BoxURLTemplateTest.java
Added path parameter sanitization. So all IDs or other path parameters that should be numeric are checked to be numeric. If they are not, the SDK throws an error. In addition, all IDs that should be alphanumeric are checked to be alphanumeric. If they are not, the SDK throws an error.
=> Add path parameter sanitization

CHANGELOG.md, src/main/java/com/box/sdk/URLTemplate.java, src/test/java/com/box/sdk/BoxURLTemplateTest.java
The SDK did not break execution and throw an exception to the user and when the sanitization check for parameters failed. This is now fixed.
=> Fix path parameter sanitization

CHANGELOG.md, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFolder.java
Calling `getIsExternallyOwned()` on `File.Info` object or `Folder.info` would cause an exception when the value is null. This is because the return type for the method was a boolean, but the value being returned was a Boolean. So when the Boolean has value null, the value could not be cast to a primitive and would throw an exception. This issue was brought up in #805. 
This is fixed by changing the type of the value being returned from a Boolean to a boolean.
=> Fix issue for `getIsExternallyOwned()` for Files and Folders

CHANGELOG.md, src/main/java/com/box/sdk/BoxClassification.java, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFolder.java, src/test/Fixtures/BoxFile/GetFileInfo200.json, src/test/Fixtures/BoxFolder/GetFolderInfo200.json, src/test/java/com/box/sdk/BoxFileTest.java, src/test/java/com/box/sdk/BoxFolderTest.java
Added classification field for `BoxFile.Info` and `BoxFolder.Info`.
=> Add support for the classification field for Files and Folders

CHANGELOG.md, src/main/java/com/box/sdk/BoxFile.java, src/test/java/com/box/sdk/BoxFileTest.java
- Added the ability to set the filename when uploading a new version of a file.
- Fixed a bug with updating the `content_modified_at` field when upload a new version
=> Add ability to set the filename when uploading a new version of a file

CHANGELOG.md, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFolder.java, src/main/java/com/box/sdk/Metadata.java, src/test/Fixtures/BoxFile/UpdateMetadataOnFile200.json, src/test/Fixtures/BoxFolder/UpdateMetadataOnFolder200.json, src/test/java/com/box/sdk/BoxFileTest.java, src/test/java/com/box/sdk/BoxFolderTest.java, src/test/java/com/box/sdk/MetadataTest.java
Box JAVA SDK uses float to set value in metadata. Metadata uses number as field type. Metadata can handle values with higher precision as compared to JAVA float e.g. setting 233333333333333340 in number field returns 2333333341.
=> Use double for metadata numbers

doc/metadata_template.md
Add orderBy and indexName parameters to `executeMetadataQuery(BoxAPIConnection api, String from, String query, JsonObject queryParameters, String ancestorFolderId, String indexName, JsonArray orderBy)` example to more closely mimic the REST API
=> Clarify how to use orderBy parameter in executeMetadataQuery

doc/folders.md
Updated the docs on getting metadata for multiple files within a folder [here](https://github.com/box/box-java-sdk/blob/31c2b82f6fbdb300561a24beef091ae837359974/doc/folders.md#get-metadata-for-multiple-files).
=> Update documentation for getting metadata

CHANGELOG.md, src/main/java/com/box/sdk/BoxSharedLink.java
unshareAt field was not working, when you set it and try to create a sharelink or update one. The reason is simple, was using default java Date toString to convert to box date what is not correct. It needs to use BoxDateFormat instead.
=> Fix bug with setting the unshared at date for a shared link

CHANGELOG.md, src/main/java/com/box/sdk/BoxCollaborator.java, src/test/Fixtures/BoxFolder/GetAllFolderCollaborations200.json, src/test/java/com/box/sdk/BoxFolderTest.java
Added support for the `type` field and the `group_type` field. This is to address issue #807.
=> Add support for more fields in `BoxCollaborator.Info`

CHANGELOG.md, src/main/java/com/box/sdk/BoxGroup.java, src/test/java/com/box/sdk/BoxGroupTest.java
`getAllGroupsByName()` was using the undocumented `name` parameter instead of `filter_term` to filter by name. Now it uses `filter_term`.
=> Update `getAllGroupsByName()` to use documented parameter

src/main/java/com/box/sdk/BoxFile.java
When external users updates a metadata instance, the scope needs to be "enterprise_xxxx".
"xxxx" is the EID of the metadata template. The current code overwrites "enterprise_xxxx" to "enterprise".
This fix allows to keep the correct scope.
=> Fix for cross-enterprise collaborator calls to updateMetadata

src/main/java/com/box/sdk/BoxSearch.java, src/main/java/com/box/sdk/BoxSearchParameters.java, src/main/java/com/box/sdk/BoxSearchSharedLink.java, src/test/Fixtures/BoxSearch/GetSearchItemsIncludingSharedLinks200.json, src/test/java/com/box/sdk/BoxSearchTest.java
When hitting the search endpoint and setting `include_recent_shared_links` to true, a different response is returned than when it's false. Now a new model and method has been added to account for this difference.
=> Fix bug with search including shared links

CHANGELOG.md, src/main/java/com/box/sdk/BoxWebLink.java, src/test/Fixtures/BoxCollection/GetCollectionItems200.json, src/test/java/com/box/sdk/BoxCollectionTest.java
=> Fix `BoxWeblink` deserialization

CHANGELOG.md, src/main/java/com/box/sdk/BoxAPIConnection.java, src/main/java/com/box/sdk/BoxFileRequest.java, src/test/Fixtures/BoxFileRequest/CopyFileRequest200.json, src/test/Fixtures/BoxFileRequest/GetFileRequest200.json, src/test/Fixtures/BoxFileRequest/UpdateFileRequest200.json, src/test/java/com/box/sdk/BoxFileRequestTest.java
From owners of FileRequest API
`This field is intended to not have host name. As there are multiple scenarios for customers (app vs. ent and subdomains), these can change at runtime. We decided to not store or return hostname prior to release.`
=> Fix FileRequest url format

src/main/java/com/box/sdk/BoxGroup.java
Wrapping a comment for javadocs generation.  (The “<” and “>” need to be escaped for HTML.)
=> Fix comment for Javadocs

src/main/java/com/box/sdk/BoxRetentionPolicy.java, src/main/java/com/box/sdk/BoxRetentionPolicyAssignment.java, src/main/java/com/box/sdk/RetentionPolicyParams.java, src/test/Fixtures/BoxRetentionPolicy/CreateRetentionPolicy201.json, src/test/Fixtures/BoxRetentionPolicy/CreateRetentionPolicyAssignmentForMetadataTemplate201.json, src/test/Fixtures/BoxRetentionPolicy/CreateRetentionPolicyAssignmentForMetadataTemplateWithoutStartDateField201.json, src/test/Fixtures/BoxRetentionPolicy/GetRetentionPolicyAssignmentInfo200.json, src/test/Fixtures/BoxRetentionPolicy/GetRetentionPolicyInfo200.json, src/test/Fixtures/BoxRetentionPolicy/UpdateRetentionPolicyInfo200.json, src/test/java/com/box/sdk/BoxRetentionPolicyAssignmentTest.java, src/test/java/com/box/sdk/BoxRetentionPolicyTest.java
Add new optional `description` parameter to the retention_policies endpoint and `start_date_field` to the retention_policy_assignments endpoint.
Closes: SDK-1839
=> feat: Add new parameters to the retention_policies and retention_policy_assignments endpoints

src/main/java/com/box/sdk/BoxEvent.java, src/main/java/com/box/sdk/EnterpriseEventsRequest.java, src/main/java/com/box/sdk/EnterpriseEventsStreamRequest.java, src/main/java/com/box/sdk/EventLog.java, src/test/java/com/box/sdk/BoxEventTest.java, src/test/java/com/box/sdk/EventLogTest.java
=> feat: Add `typeName` to `BoxEvent` that contains name of the event, even if it is not mapped to `BoxEvent.EventType`

doc/authentication.md
Correct sample code tag, so it [developer.box.com](https://developer.box.com/guides/authentication/client-credentials/) correctly display sample code.
=> fix: Documentation Client credentials grant sample code tag

doc/authentication.md, doc/events.md, doc/folders.md
Blank line between the sample tag and markdown
=> fix: Documentation - Add missing blank line after code tag

doc/authentication.md
Add blank space between markdown and sample code tag, so developer website can pull sample code.
=> docs: Authentication sample code  - add blank space

src/main/java/com/box/sdk/BoxAPIConnection.java, src/main/java/com/box/sdk/SharedLinkAPIConnection.java
Removed methods getMaxRequestAttempts and setMaxRequestAttempts. Still we are reading values from JSON if someone has still stored it somewhere and restoring API connection from JSON.
=> chore: Removed deprecated methods

src/main/java/com/box/sdk/BoxAPIConnection.java
Issue: [OAUTH_SUFFIX gets appended twice to baseAuthorizationURL #1147](https://github.com/box/box-java-sdk/issues/1147)
Code changes:
* Removed unnecessary append of `OAUTH_SUFFIX`
=> fix: `OAUTH_SUFFIX` gets appended twice to `baseAuthorizationURL`

src/main/java/com/box/sdk/BoxAPIConnection.java, src/test/java/com/box/sdk/BoxAPIConnectionTest.java
=> fix: Fallback to default value of `maxRetryAttempts` when restoring `BoxAPIConnection`

src/main/java/com/box/sdk/BoxAPIResponse.java, src/main/java/com/box/sdk/BoxJSONRequest.java, src/main/java/com/box/sdk/BoxJSONResponse.java, src/test/java/com/box/sdk/BoxJSONRequestTest.java
=> fix: class cast exception when uploading large file

src/intTest/java/com/box/sdk/BoxFileIT.java, src/intTest/java/com/box/sdk/MetadataIT.java, src/main/java/com/box/sdk/BoxCollaboration.java, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFolder.java, src/test/Fixtures/BoxFolder/GetAllFolderCollaborations200.json, src/test/Fixtures/BoxFolder/GetAllFolderCollaborations200WithFields.json, src/test/java/com/box/sdk/BoxCollaborationTest.java, src/test/java/com/box/sdk/BoxFolderTest.java
=> feat: Getting collaborators allows to specify fields

src/intTest/java/com/box/sdk/BoxFolderIT.java, src/main/java/com/box/sdk/AbstractBoxMultipartRequest.java, src/main/java/com/box/sdk/BinaryBodyUtils.java, src/main/java/com/box/sdk/FileUploadParams.java, src/main/java/com/box/sdk/ProgressListener.java, src/main/java/com/box/sdk/RequestBodyFromStream.java, src/test/java/com/box/sdk/RequestBodyFromStreamTest.java
With OkHttp not really working with stream we have our own solution. But it can work with them as long as we tell it that content size if unknown.
This was the source of the problem in the #1183 where two threads started and one was feeding data to other. First was downloading a file second was uploading new version.
This should also address failing uploads when dealing with a stream which full size cannot be determined upfront (#1190 ).
=> fix: Fixed upload when data are coming from a dynamic source

doc/collaborations.md, doc/files.md, doc/folders.md, src/intTest/java/com/box/sdk/BoxCollaborationIT.java, src/main/java/com/box/sdk/BoxCollaboration.java, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFolder.java, src/test/Fixtures/BoxCollaboration/CreateCollaboration201.json, src/test/Fixtures/BoxCollaboration/CreateFileCollaboration201.json, src/test/Fixtures/BoxCollaboration/GetCollaborationInfo200.json, src/test/Fixtures/BoxCollaboration/GetCollaborationOnFolder200.json, src/test/Fixtures/BoxCollaboration/GetPendingCollaborationInfo200.json, src/test/Fixtures/BoxCollaboration/UpdateCollaboration200.json, src/test/java/com/box/sdk/BoxCollaborationTest.java, src/test/java/com/box/sdk/BoxFileTest.java, src/test/java/com/box/sdk/BoxFolderTest.java
=> feat: Support access only collaboration

doc/sign_templates.md, src/main/java/com/box/sdk/BoxSignRequest.java, src/main/java/com/box/sdk/BoxSignRequestCreateParams.java, src/main/java/com/box/sdk/BoxSignTemplate.java, src/test/Fixtures/BoxSignRequest/CancelSignRequest200.json, src/test/Fixtures/BoxSignRequest/CreateSignRequest200.json, src/test/Fixtures/BoxSignRequest/GetAllSignRequests200.json, src/test/Fixtures/BoxSignRequest/GetSignRequest200.json, src/test/Fixtures/BoxSignTemplate/GetAllSignTemplates200.json, src/test/Fixtures/BoxSignTemplate/GetSignTemplateInfo200.json, src/test/java/com/box/sdk/BoxSignRequestTest.java, src/test/java/com/box/sdk/BoxSignTemplateTest.java
=> feat: Support sign template and new sign status

src/main/java/com/box/sdk/BoxSignRequestSigner.java, src/test/Fixtures/BoxSignRequest/CreateSignRequest200.json, src/test/Fixtures/BoxSignRequest/GetAllSignRequests200.json, src/test/Fixtures/BoxSignRequest/GetSignRequest200.json, src/test/java/com/box/sdk/BoxSignRequestTest.java
=> feat: Add `iframeable_embed_url` field to `BoxSignRequestSigner` class

README.md, build.gradle
=> build: Bumped `org.bitbucket.b_c:jose4j:0.9.3`

src/intTest/java/com/box/sdk/BoxCollaborationAllowlistIT.java, src/intTest/java/com/box/sdk/BoxRetentionPolicyAssignmentIT.java, src/intTest/java/com/box/sdk/BoxSignRequestIT.java, src/intTest/java/com/box/sdk/BoxUserIT.java, src/intTest/java/com/box/sdk/CleanupTools.java, src/main/java/com/box/sdk/BoxSignRequestSigner.java, src/main/java/com/box/sdk/BoxSignTemplateSigner.java
=> feat: Add `signer_group_id` for signer in sign request

src/intTest/java/com/box/sdk/BoxFileIT.java, src/main/java/com/box/sdk/BoxAPIResponse.java
Fixes #1230 
Remove unecessary contentLength check for stream response
=> fix: fix download for empty files

doc/files.md, src/intTest/java/com/box/sdk/BoxFileIT.java, src/intTest/java/com/box/sdk/UniqueTestFolder.java, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFileVersion.java, src/test/java/com/box/sdk/BoxFileTest.java
=> feat: Support pagination of file versions

doc/files.md, src/test/java/com/box/sdk/BoxFolderTest.java
=> docs: Update file uploads docs

src/intTest/java/com/box/sdk/BoxSignRequestIT.java, src/main/java/com/box/sdk/BoxSignRequestSigner.java, src/main/java/com/box/sdk/BoxWebHook.java, src/test/Fixtures/BoxSignRequest/CreateSignRequest200.json, src/test/Fixtures/BoxSignRequest/GetSignRequest200.json, src/test/java/com/box/sdk/BoxSignRequestTest.java
Closes: [SDK-3826](https://jira.inside-box.net/browse/SDK-3826)
=> feat: Support `login_required`, `password`, `suppress_nofitications`, `verification_phone_number` and `additional_info` fields in sign request

src/main/java/com/box/sdk/BoxDeveloperEditionAPIConnection.java
=> feat: make `tryRestoreUsingAccessTokenCache` in Box API connection public

src/main/java/com/box/sdk/BoxAPIConnection.java, src/main/java/com/box/sdk/BoxSensitiveDataSanitizer.java, src/test/java/com/box/sdk/BoxSensitiveDataSanitizerTest.java
- should clean headers containing potentially sensitive data when request is directly logged and replace them with `[REDACTED]`
- list of sensitive keys taken from https://github.com/box/box-python-sdk/blob/e5c60b2718cb2be755da0fc6c51f73caa285c3a1/boxsdk/util/log.py#L13
=> fix: remove sensitive data when `BoxAPIException` logs request

README.md, build.gradle, src/intTest/java/com/box/sdk/BoxFileIT.java, src/main/java/com/box/sdk/BoxAPIConnection.java, src/main/java/com/box/sdk/BoxGlobalSettings.java, src/main/java/com/box/sdk/ZstdInterceptor.java, src/test/java/com/box/sdk/BoxAPIRequestTest.java
Support use zstd encoding while downloading files.
=> feat: Support `zstd` encoding for downloads

.github/workflows/build-main.yml, .github/workflows/integration-tests.yml, .github/workflows/spell-check-lint.yml, src/main/java/com/box/sdk/BoxAIItem.java, src/main/java/com/box/sdk/BoxAPIResponse.java, src/main/java/com/box/sdk/BoxCollaboration.java, src/main/java/com/box/sdk/BoxCollaborator.java, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFileRequest.java, src/main/java/com/box/sdk/BoxFolder.java, src/main/java/com/box/sdk/BoxGroupMembership.java, src/main/java/com/box/sdk/BoxSensitiveDataSanitizer.java, src/main/java/com/box/sdk/BoxSharedLink.java, src/main/java/com/box/sdk/BoxUploadEmail.java, src/main/java/com/box/sdk/BoxUser.java, src/main/java/com/box/sdk/BoxZipDownloadStatus.java, src/main/java/com/box/sdk/MetadataQuery.java, src/main/java/com/box/sdk/RetentionPolicyParams.java, src/main/java/com/box/sdk/internal/utils/JsonUtils.java, src/test/java/com/box/sdk/BoxTaskTest.java, src/test/java/com/box/sdk/BoxUserTest.java
Fixes https://github.com/box/box-java-sdk/issues/1305
- Use Locale.ROOT in `toLowerCase` and `toUpperCase` to prevent unwanted conversion on characters on turkish locale (see comment for https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/lang/String.java#L3743)
- Fix github actions 322 code error by bumping version of used actions. Issue was most likely caused by using outdated version of https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/ somewhere in our actions
=> fix: use `Locale.ROOT` to prevent issues with non-US locales

src/main/java/com/box/sdk/BoxZipDownloadStatus.java
API call returns "downloaded_file_count" not "download_file_count"..  As such object is not representing the correct download count.
=> fix: Fix parsing `downloadFileCount` property for `BoxZipDownloadStatus`
