box/box-java-sdk

src/main/java/com/box/sdk/BoxEvent.java
Fixes #55 
While this isn't fully documented, the documentation is being updated shortly, and will reflect this change soon.
=> Added COLLAB_ROLE_CHANGE

src/main/java/com/box/sdk/BoxAPIRequest.java
To be able to inspect the request a little bit, the first step is to be able to be able to extract out the URL, so I exposed this in a function.
=> Exposed URL from a BoxAPIRequest

src/main/java/com/box/sdk/BoxUser.java, src/main/java/com/box/sdk/CreateUserParams.java, src/test/java/com/box/sdk/BoxUserTest.java, src/test/java/com/box/sdk/JSONRequestInterceptor.java
This change adds `createEnterpriseUser()` methods to `BoxUser`. The
basic form of this method creates a new user with a login and name. The
more advanced implementation can take a `CreateUserParams` object which
allows for fully customizing the details about the new user.
For testing, a new `JSONRequestInterceptor` class was added in order to
make it easier to inspect the JSON that would be sent in a request.
=> Create new enterprise user

src/main/java/com/box/sdk/BoxEnterprise.java, src/main/java/com/box/sdk/BoxJSONObject.java, src/main/java/com/box/sdk/BoxUser.java, src/test/java/com/box/sdk/BoxUserTest.java
This change allows a user's information to be updated by setting fields
in `BoxUser.Info` and then calling `updateInfo()` on a `BoxUser` object.
=> Update a user's info

src/main/java/com/box/sdk/BoxUser.java, src/main/java/com/box/sdk/EmailAlias.java, src/test/java/com/box/sdk/BoxUserTest.java
Add a method called `getEmailAliases()` to `BoxUser` that retrieves all
the email aliases associated with a user.
=> Get all email aliases for a user

src/main/java/com/box/sdk/BoxUser.java, src/test/java/com/box/sdk/BoxUserTest.java
This change adds an `addEmailAlias()` method to `BoxUser` that adds a
new email alias to the user's account.
=> Add new email alias for a user

src/main/java/com/box/sdk/JSONIterator.java
=> Fix #98 BoxGroupIterator.next() causes NPE

src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFolder.java
An updated PR for #59 and closes #47 
(my git history messed up a bunch, so I thought it would be cleaner to just push a new branch)
=> Added optional functions to use the preflight upload api checks to BoxFolder and BoxFile

src/main/java/com/box/sdk/BoxAPIConnection.java, src/main/java/com/box/sdk/BoxAPIRequest.java
Update BoxAPIConnection so that the proxy configuration (along with
other connection-level settings) is applied when performing OAuth
requests.
Closes #142.
=> Use proxy when authenticating

.gitignore, src/main/java/com/box/sdk/BoxDeveloperEditionAPIConnection.java
=> added whitespace after switch statement to satisfy checkStyleMain

src/main/java/com/box/sdk/EventLog.java
I simply changed the type of the stream position fields and parameters from long to String. As Greg pointed out in the issue the nature of the issue requires a breaking change and major version bump.
=> Fixed #185 by changing type of stream position from long to String

src/main/java/com/box/sdk/BoxAPIRequest.java, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxRedirectResponse.java, src/test/java/com/box/sdk/BoxFileTest.java
=> Get download url

src/main/java/com/box/sdk/BoxFile.java, src/test/java/com/box/sdk/BoxFileTest.java
=> adds method to retrieve the thumbnail image for a file

src/example/java/com/box/sdk/example/AccessAsAppUser.java, src/example/java/com/box/sdk/example/AccessTokenCache.java, src/example/java/com/box/sdk/example/CreateAppUser.java, src/main/java/com/box/sdk/BoxAPIConnection.java, src/main/java/com/box/sdk/BoxDeveloperEditionAPIConnection.java, src/main/java/com/box/sdk/IAccessTokenCache.java, src/main/java/com/box/sdk/InMemoryLRUAccessTokenCache.java, src/test/java/com/box/sdk/BoxAPIConnectionTest.java, src/test/java/com/box/sdk/TestConfig.java
=> Token caching refactoring

src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxMetadataFilter.java, src/main/java/com/box/sdk/Metadata.java, src/main/java/com/box/sdk/QueryStringBuilder.java
* Added getMetadata(template, scope) to specify template scope
* Added Metadata.getKeys() to return the list of keys
* Fixed bug in URL encoder not encoding some characters
* Fixed bug in metadata search incorrectly forcing lower case
=> Metadata fixes

README.md, doc/tasks.md, src/main/java/com/box/sdk/BoxGroup.java
Adds documentation for `BoxTask` and a couple other minor fixes
=> Missing documentation

doc/tasks.md
Some stuff I noticed I missed in my initial patchset
=> Task documentation corrections

doc/groups.md, src/test/java/com/box/sdk/BoxGroupTest.java
Test + docs for #218 
@maurercw @gcurtis @codyebberson
=> Add test and docs for BoxGroup.getCollaborations()

doc/files.md, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxLock.java, src/test/java/com/box/sdk/BoxFileTest.java
Initial attempt at file lock/unlock implementation
=> Implement file lock/unlock

src/main/java/com/box/sdk/BoxFolder.java, src/main/java/com/box/sdk/BoxMultipartRequest.java, src/test/java/com/box/sdk/BoxFileTest.java, src/test/java/com/box/sdk/BoxMultipartRequestTest.java
Address #150 by specifying the filename (and parent id) in JSON instead of the Content-Disposition header
@gcurtis @codyebberson @dmaynard
=> Fix filename truncation #150

src/main/java/com/box/sdk/BoxFolder.java, src/main/java/com/box/sdk/BoxItemIterator.java, src/main/java/com/box/sdk/BoxResource.java, src/main/java/com/box/sdk/BoxWebLink.java, src/test/java/com/box/sdk/BoxFolderTest.java, src/test/java/com/box/sdk/BoxWebLinkTest.java
=> Add support for BoxWebLink

.gitignore, build.gradle, config/checkstyle/checkstyle.xml, src/main/java/com/box/sdk/BoxCollaboration.java, src/main/java/com/box/sdk/BoxComment.java, src/main/java/com/box/sdk/BoxEvent.java, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFileVersion.java, src/main/java/com/box/sdk/BoxFolder.java, src/main/java/com/box/sdk/BoxGroup.java, src/main/java/com/box/sdk/BoxGroupMembership.java, src/main/java/com/box/sdk/BoxJSONObject.java, src/main/java/com/box/sdk/BoxResource.java, src/main/java/com/box/sdk/BoxResourceIterable.java, src/main/java/com/box/sdk/BoxResourceType.java, src/main/java/com/box/sdk/BoxTask.java, src/main/java/com/box/sdk/BoxTaskAssignment.java, src/main/java/com/box/sdk/BoxUser.java, src/main/java/com/box/sdk/BoxWebHook.java, src/main/java/com/box/sdk/BoxWebHookSignatureVerifier.java, src/main/java/com/box/sdk/BoxWebLink.java, src/main/java/com/box/sdk/internal/package-info.java, src/main/java/com/box/sdk/internal/pool/MacPool.java, src/main/java/com/box/sdk/internal/utils/CollectionUtils.java, src/test/java/com/box/sdk/BoxResourceTest.java, src/test/java/com/box/sdk/BoxWebHookSignatureVerifierTest.java, src/test/java/com/box/sdk/BoxWebHookTest.java, src/test/java/com/box/sdk/internal/utils/CollectionUtilsTest.java
Adding support for webhooks v2
=> Adding support for webhooks V2

src/main/java/com/box/sdk/BoxEvent.java
Updated the event type to include the new events in the V2 API from https://docs.box.com/reference#events
=> Added new Event Types

build.gradle
Updating version to 2.2.2-SNAPSHOT
=> Updating version to 2.2.2-SNAPSHOT

README.md, doc/collections.md, src/main/java/com/box/sdk/BoxCollection.java, src/main/java/com/box/sdk/BoxCollectionIterator.java, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFolder.java, src/main/java/com/box/sdk/BoxItem.java, src/main/java/com/box/sdk/BoxResource.java, src/main/java/com/box/sdk/BoxWebLink.java, src/test/java/com/box/sdk/BoxCollectionTest.java, src/test/java/com/box/sdk/BoxFileTest.java
=> Implement collections

src/main/java/com/box/sdk/BoxMultipartRequest.java, src/test/java/com/box/sdk/BoxMultipartRequestTest.java
Added the -- to the last boundary to fix and issue when going through
Layer7.
Closes #334.
=> Add -- to last boundary

doc/folders.md, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFolder.java, src/main/java/com/box/sdk/Metadata.java, src/test/java/com/box/sdk/BoxFolderTest.java
This includes creating, retrieving, updating and deleting metadata on a folder.
Closes #350.
Closes #351.
Closes #353.
Closes #354.
=> Implement basic folder metadata CRUD

README.md, doc/devices.md, src/main/java/com/box/sdk/BoxDevicePin.java, src/main/java/com/box/sdk/BoxResource.java, src/main/java/com/box/sdk/BoxResourceIterable.java, src/test/java/com/box/sdk/BoxDevicePinTest.java, src/test/java/com/box/sdk/BoxResourceIterableTest.java
"Get Enterprise Device Pins" and "Delete Device Pin" features implementation, tests and documentation.
Contains all the code from [Get Device Pin](https://github.com/box/box-java-sdk/pull/305)
=> Get Enterprise Device Pins and Delete Device Pin features

README.md, doc/retention_policies.md, src/main/java/com/box/sdk/BoxResource.java, src/main/java/com/box/sdk/BoxRetentionPolicy.java, src/test/java/com/box/sdk/BoxRetentionPolicyTest.java
Create retention policy feature implemented as createFinitePolicy(..) and createIndefinitePolicy(..) methods of BoxRetentionPolicy class.
Update retention policy feature implemented as updateInfo(..) method of BoxRetentionPolicy class.
Get retention policy feature implemented as getInfo(..) method of BoxRetentionPolicy class.
Get retention policies feature implemented as getAll(..) methods of BoxRetentionPolicy class.
Methods are covered with unit tests and documented.
=> Retention Policy basic features

README.md, doc/retention_policies.md, src/main/java/com/box/sdk/BoxFileVersionRetention.java, src/main/java/com/box/sdk/BoxResource.java, src/main/java/com/box/sdk/BoxRetentionPolicy.java, src/test/java/com/box/sdk/BoxFileVersionRetentionTest.java, src/test/java/com/box/sdk/BoxRetentionPolicyTest.java
Get File Version Retention feature implemented as getInfo(..) method of BoxFileVersionRetention object.
Get File Version Retentions feature implementes as getAll(..) and getRetentions(..) methods of BoxFileVersionRetention object.
Methods are tested and documented.
This pull request contains code from [Retention Policy basic features](https://github.com/box/box-java-sdk/pull/317) and markdown documentation for all Retention Policies features to reduce future merge conflicts.
=> File Version Retention features

README.md, doc/webhooks.md, src/main/java/com/box/sdk/BoxWebHook.java, src/test/java/com/box/sdk/BoxWebHookTest.java
Unit tests for BoxWebhook and BoxResourceIterable;
Markdown docs for webhooks.
=> Webhook features tests and docs

README.md, doc/weblinks.md, src/test/java/com/box/sdk/BoxFolderTest.java, src/test/java/com/box/sdk/BoxWebLinkTest.java
unit tests for BoxWeblink methods
Made a local branch of Hotovo's branch and did a manual merge.  Also changed continuation indent from 8 to 4 because it resulted in LESS diffs when reformating the code.
=> Hotovo feature/weblink

README.md, doc/weblinks.md, src/test/java/com/box/sdk/BoxFolderTest.java, src/test/java/com/box/sdk/BoxWebLinkTest.java
Unit tests for BoxWebLink and web link related BoxFolder method.
=> Web Links related unit tests

src/test/java/com/box/sdk/BoxUserTest.java
Unit tests for:
Delete Email Alias
Delete User
Get Current User
Get User's Info
Move User's Folder
=> BoxUser Unit tests

doc/files.md, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxItem.java, src/main/java/com/box/sdk/Metadata.java, src/test/java/com/box/sdk/BoxFileTest.java
Get All Metadata on File feature implementation and testing;
BoxResourceIterable testing;
Wildcard imports resolved.
=> Get All Metadata on File

doc/folders.md, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFolder.java, src/main/java/com/box/sdk/BoxItem.java, src/main/java/com/box/sdk/Metadata.java, src/test/java/com/box/sdk/BoxFileTest.java, src/test/java/com/box/sdk/BoxFolderTest.java
"Get all metadata on folder" feature implementation, unit tests and markdown documentation.
Contains code from [Get All Metadata on File](https://github.com/box/box-java-sdk/pull/314)
=> Get All Metadata on Folder

doc/groups.md, src/main/java/com/box/sdk/BoxGroup.java, src/main/java/com/box/sdk/BoxGroupMembership.java, src/main/java/com/box/sdk/BoxGroupMembershipIterator.java, src/main/java/com/box/sdk/BoxUser.java, src/test/java/com/box/sdk/BoxGroupMembershipTest.java, src/test/java/com/box/sdk/BoxGroupTest.java, src/test/java/com/box/sdk/BoxUserTest.java
"Update group" feature implementation, tests and documentation.
Should be reviewed after [Groups and Memberships tests and paging](https://github.com/box/box-java-sdk/pull/310)
=> Update Group feature implemented

build.gradle, doc/legal_holds.md, src/main/java/com/box/sdk/BoxLegalHoldAssignment.java, src/main/java/com/box/sdk/BoxLegalHoldPolicy.java, src/main/java/com/box/sdk/BoxResource.java, src/test/java/com/box/sdk/BoxLegalHoldPolicyAssignmentTest.java, src/test/java/com/box/sdk/BoxLegalHoldPolicyTest.java
Cloned from Hotovofeature/legal hold advanced with BoxLegalHold class renamed to BoxLegaHoldPolicy to match API documents.
=> Hotovo feature/legal hold advanced

doc/legal_holds.md, src/main/java/com/box/sdk/BoxFileVersion.java, src/main/java/com/box/sdk/BoxFileVersionLegalHold.java, src/main/java/com/box/sdk/BoxLegalHold.java, src/main/java/com/box/sdk/BoxLegalHoldAssignment.java, src/main/java/com/box/sdk/BoxResource.java, src/test/java/com/box/sdk/BoxFileVersionLegalHoldTest.java, src/test/java/com/box/sdk/BoxLegalHoldAssignmentTest.java, src/test/java/com/box/sdk/BoxLegalHoldTest.java
Get Assignment feature implemented as getInfo(..) method of BoxLegalHoldAssignment object;
Get List of Assignments feature implemented as getAssignments(..) methods of BoxLegalHold object;
Create New Assignment feature implemented as assignTo(..) method of BoxLegalHold object;
Delete Assignment implemented as delete() method of BoxLegalHoldAssignment object;
Get File Version Legal Hold feature implemented as getInfo(..) method of BoxFileVersionLegalHold object;
Get List of File Version Legal Holds feature implemented as getFileVersionHolds(..) method of BoxLegalHold object.
Methods are tested and documented.
This branch contains all code from [Legal Holds basic features](https://github.com/box/box-java-sdk/pull/358)
=> Legal Holds advanced features

doc/users.md
Markdown documentation for closed [pull request](https://github.com/box/box-java-sdk/pull/293) with Invite User feature implementation.
=> Invite User markdown documentation

README.md, doc/metadata_template.md, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/MetadataTemplate.java, src/test/java/com/box/sdk/MetadataTemplateTest.java
"Get Metadata Template" and "Get Enterprise Metadata" features implemented as functions of introduced MetadataTemplate object. Functions were documented and covered with unit tests.
=> Get Metadata Template and Get Enterprise Metadata features

src/main/java/com/box/sdk/BoxTask.java, src/main/java/com/box/sdk/BoxTaskAssignment.java, src/main/java/com/box/sdk/BoxTaskAssignmentIterator.java, src/test/java/com/box/sdk/BoxFileTest.java, src/test/java/com/box/sdk/BoxTaskAssignmentTest.java, src/test/java/com/box/sdk/BoxTaskTest.java
Added "fields" param support for Get Task, Get Task Assignment and Get Assignments features;
Added paging support for Get Assignments;
Added opportunity to create Task Assignment [using user's login](https://docs.box.com/reference#create-a-task-assignment);
Methods were covered with unit tests.
=> Fixes and unit tests for Tasks

doc/groups.md, src/main/java/com/box/sdk/BoxGroup.java, src/main/java/com/box/sdk/BoxGroupMembership.java, src/main/java/com/box/sdk/BoxGroupMembershipIterator.java, src/main/java/com/box/sdk/BoxUser.java, src/test/java/com/box/sdk/BoxGroupMembershipTest.java, src/test/java/com/box/sdk/BoxGroupTest.java, src/test/java/com/box/sdk/BoxUserTest.java
Paging implementation for Get Memberships features;
"fields" query param support added;
Unit tests for Groups and Memberships;
Javadocs for Groups and Memberships.
=> Groups and Memberships tests and paging

build.gradle, config/checkstyle/suppressions.xml, src/main/java/com/box/sdk/BoxCollaboration.java, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFolder.java, src/main/java/com/box/sdk/BoxResourceIterable.java, src/test/java/com/box/sdk/BoxCollaborationTest.java, src/test/java/com/box/sdk/BoxFolderTest.java, src/test/java/com/box/sdk/IntegrationTestDebug.java
oxResourceIterSingle file collaborations.   Also fixed bug in BocResourceIterable which was causing the new style paging Iterators to loop indefinitely.
=> Singlefilecollab

src/main/java/com/box/sdk/BoxAPIRequest.java, src/main/java/com/box/sdk/BoxConfig.java, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFileUploadSession.java, src/main/java/com/box/sdk/BoxFolder.java, src/main/java/com/box/sdk/LargeFileUpload.java, src/test/java/com/box/sdk/BoxFileTest.java
1. URL endpoint change from upload-session to upload_sessions
2. 'upload_session_id' field is just 'id' now
3. Removed 'partId' header from upload session part API
=> Handling changes in the multiput upload apis which include

doc/files.md, doc/search.md, src/main/java/com/box/sdk/BoxAPIConnection.java, src/main/java/com/box/sdk/BoxAPIException.java, src/main/java/com/box/sdk/BoxFileUploadSession.java, src/main/java/com/box/sdk/BoxFileUploadSessionPartList.java, src/main/java/com/box/sdk/LargeFileUpload.java, src/main/java/com/box/sdk/ScopedToken.java, src/test/java/com/box/sdk/BoxAPIConnectionTest.java, src/test/java/com/box/sdk/BoxFileTest.java, src/test/java/com/box/sdk/BoxFolderTest.java
https://developer.box.com/docs/getting-started-with-new-box-view#section-retrieve-a-file-token-using-token-exchange-optional
=> Token exchange

src/main/java/com/box/sdk/BoxDeveloperEditionAPIConnection.java
=> Fixing BoxDeveloperEditionAPIConnection - decryptPrivateKey() - PEMParser returns PrivateKeyInfo already - Invalid cast #470

src/main/java/com/box/sdk/BoxComment.java, src/test/java/com/box/sdk/BoxCommentTest.java
=> Add modified_at timestamp to BoxComment.Info

src/main/java/com/box/sdk/BoxEvent.java
=> Add missing event types to enum

src/main/java/com/box/sdk/BoxWebHook.java
=> Add missing webhook triggers to enum

doc/metadata_template.md
Closed a github issue about metadata template and then realized there was no documentation on how to add fields nor create template
=> Metadata readme patch

doc/metadata_template.md
=> Document Update Metadata Template method

src/main/java/com/box/sdk/BoxAPIConnection.java, src/test/java/com/box/sdk/BoxAPIConnectionTest.java
=> Add support for token revocation

doc/collaborations.md, src/main/java/com/box/sdk/BoxCollaboration.java, src/test/java/com/box/sdk/BoxCollaborationTest.java
=> Allow retrieving Collaboration fields

src/main/java/com/box/sdk/BoxAPIRequest.java, src/test/java/com/box/sdk/BoxAPIRequestTest.java
=> Fix check for duplicate As-User headers

doc/webhooks.md
=> changed BOX-SIGNATURE-VERSION to BOX-SIGNATURE-ALGORITH

src/main/java/com/box/sdk/BoxAPIRequest.java
Resolution was to use a static reference to the SSL Socket Factory, rather than getting it each time from the SSLContext.
=> Resolution for issue #642 JDK TCP CONNECTION ISSUE

src/main/java/com/box/sdk/BoxItem.java, src/test/java/com/box/sdk/BoxFileTest.java, src/test/java/com/box/sdk/BoxFolderTest.java
=> Expose object type on BoxItem

src/main/java/com/box/sdk/BoxFolder.java, src/main/java/com/box/sdk/BoxMultipartRequest.java, src/main/java/com/box/sdk/FileUploadParams.java, src/main/java/com/box/sdk/UploadFileCallback.java, src/test/java/com/box/sdk/BoxFolderTest.java, src/test/java/com/box/sdk/BoxMultipartRequestTest.java
Feature Request : Allow content streaming to box through outputstream.
Closes : #666
=> Allow content streaming to box through outputstream.

doc/files.md, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFolder.java, src/main/java/com/box/sdk/LargeFileUpload.java, src/test/Fixtures/BoxFile/CommitUploadWithAttributes201.json, src/test/java/com/box/sdk/BoxFileTest.java, src/test/java/com/box/sdk/BoxFolderTest.java
Added ability to set file attributes when uploading large files
Closes #729
=> Set file attributes on chunked uploads

doc/metadata_template.md, src/main/java/com/box/sdk/BoxUser.java
Also updated old links to docs.
=> Add additional metadata template samples for dev docs. Update old links

CHANGELOG.md, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxWebLink.java, src/test/java/com/box/sdk/BoxFileTest.java, src/test/java/com/box/sdk/BoxWebLinkTest.java
Resolves https://github.com/box/box-java-sdk/issues/777
=> Fix bug with premature disconnect in File Rename

CHANGELOG.md, src/main/java/com/box/sdk/BoxCollaboration.java, src/test/Fixtures/BoxCollaboration/CreateCollaboration201.json, src/test/Fixtures/BoxCollaboration/UpdateCollaboration200.json, src/test/java/com/box/sdk/BoxCollaborationTest.java
Added the ability to set the expiration date when creating or updating a collaboration. Addresses this issue #770.
=> Add ability to set expiration date for a collaboration

CHANGELOG.md, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFileVersion.java, src/test/Fixtures/BoxFile/GetFileInfo200.json, src/test/java/com/box/sdk/BoxFileTest.java, src/test/java/com/box/sdk/BoxFileVersionTest.java
Added the uploader display name field to the `BoxFile` and `BoxFileVersion` models
=> Add support for the uploader display name field for Files and File Versions

doc/events.md
Fix the tag for a documentation sample
=> Fix sample tag

src/main/java/com/box/sdk/BoxGroup.java, src/test/Fixtures/BoxGroup/GetGroupsByNameWithFieldsOption200.json, src/test/java/com/box/sdk/BoxGroupTest.java
=> Add ability to get groups by name with fields option (#786)

src/main/java/com/box/sdk/BoxAPIConnection.java
- Adds folder API endpoint matching to determine a downscope token request resource attribute value
=> token downscoping for folders endpoints

doc/zip_download.md
Added sample tags for developer documentation
=> Add Zip Download sample tags

src/main/java/com/box/sdk/BoxCollaboration.java
=> Update file collaborations URL template

doc/classifications.md
Updated the code samples to use constants.
=> Use constants in classification samples

doc/users.md
We changed the ID of this endpoint in the dev docs and therefore the samples need new IDs as well.
=> Update sample tag for transfer folder

CHANGELOG.md, src/main/java/com/box/sdk/BoxUser.java, src/test/java/com/box/sdk/BoxUserTest.java
In response to #853. Tracking codes were being formatted incorrectly in the body of the requests.
=> Fix bug with updating tracking codes

src/main/java/com/box/sdk/BoxFile.java
=> Add support for more user permissions on a File

.github/ISSUE_TEMPLATE/config.yml, .travis.yml, CONTRIBUTING.md
To update your existing local environment, run these commands:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
=> Update default branch from `master` to `main`

CHANGELOG.md, doc/legal_holds.md, src/main/java/com/box/sdk/BoxLegalHoldPolicy.java, src/test/java/com/box/sdk/BoxLegalHoldPolicyTest.java
Fixes https://github.com/box/box-java-sdk/issues/868
=> Add legal hold policy setters

CHANGELOG.md, src/main/java/com/box/sdk/BoxGroup.java, src/main/java/com/box/sdk/BoxGroupMembership.java, src/test/java/com/box/sdk/BoxGroupMembershipTest.java
=> Add support for configurable permission to box group

doc/collaborations.md
this adds a sample tag for collaborating with groups. ddoc 464
=> Adding group variant for devdocs

src/main/java/com/box/sdk/BoxTermsOfServiceUserStatus.java
=> Fix method overload

src/main/java/com/box/sdk/BoxEvent.java
This Pull request pushes enhancement #974 - Missing eventTypes from BoxAPI Documents
=> feat: Missing eventTypes from BoxAPI Documents

src/intTest/java/com/box/sdk/BoxFolderIT.java, src/intTest/java/com/box/sdk/BoxRetentionPolicyAssignmentIT.java, src/intTest/java/com/box/sdk/BoxTrashIT.java, src/intTest/java/com/box/sdk/BoxUserIT.java, src/intTest/java/com/box/sdk/UniqueTestFolder.java, src/main/java/com/box/sdk/BoxFileVersion.java, src/main/java/com/box/sdk/BoxFileVersionLegalHold.java, src/main/java/com/box/sdk/BoxFileVersionRetention.java, src/main/java/com/box/sdk/BoxRetentionPolicy.java, src/main/java/com/box/sdk/BoxRetentionPolicyAssignment.java, src/test/java/com/box/sdk/BoxFileTest.java, src/test/java/com/box/sdk/BoxRetentionPolicyAssignmentTest.java
- fix!: `BoxRetentionPolicyAssignment#getFileVersionsUnderRetention` returns `Iterable<BoxFileTest.Info>` and not `Iterable<BoxFileVersion>`.
=> fix!: Changed BoxFileVersion class and removed fileVersion field

build.gradle, src/intTest/java/com/box/sdk/MetadataTemplateIT.java, src/intTest/java/com/box/sdk/RetentionPolicyUtils.java, src/main/java/com/box/sdk/MetadataQuery.java, src/main/java/com/box/sdk/MetadataTemplate.java, src/test/config/config.properties.template, src/test/java/com/box/sdk/MetadataQueryTest.java, src/test/java/com/box/sdk/MetadataTemplateTest.java
- feat: introducing MetadataQuery to simplify query building
=> feat: Deprecating `indexName` when executing metadata query

src/intTest/java/com/box/sdk/BoxRetentionPolicyAssignmentIT.java, src/intTest/java/com/box/sdk/BoxTrashIT.java, src/main/java/com/box/sdk/BoxAPIRequest.java, src/test/java/com/box/sdk/BoxAPIRequestTest.java
=> fix: retry `jwt` auth when error code is in error field

doc/files.md, doc/folders.md, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFolder.java
=> docs: Update metadata documentation for a file and folder

doc/configuration.md, src/main/java/com/box/sdk/BoxAPIConnection.java, src/test/java/com/box/sdk/BoxAPIConnectionTest.java
=> fix: Fix getting proper URL to authenticate with OAuth

src/main/java/com/box/sdk/BoxSignRequest.java, src/main/java/com/box/sdk/BoxSignRequestCreateParams.java, src/main/java/com/box/sdk/BoxSignRequestSigner.java, src/test/Fixtures/BoxSignRequest/CancelSignRequest200.json, src/test/Fixtures/BoxSignRequest/CreateSignRequest200.json, src/test/Fixtures/BoxSignRequest/GetAllSignRequests200.json, src/test/Fixtures/BoxSignRequest/GetSignRequest200.json, src/test/java/com/box/sdk/BoxSignRequestTest.java
Closes: [SDK-2356](https://jira.inside-box.net/browse/SDK-2356)
=> feat: Add `redirect_url` and `declined_redirect_url` to Sign Request

src/intTest/java/com/box/sdk/BoxRetentionPolicyAssignmentIT.java, src/intTest/java/com/box/sdk/RetentionPolicyUtils.java, src/main/java/com/box/sdk/BoxRetentionPolicy.java, src/main/java/com/box/sdk/BoxRetentionPolicyAssignment.java, src/main/java/com/box/sdk/RetentionPolicyParams.java, src/test/Fixtures/BoxRetentionPolicy/CreateRetentionPolicy201.json, src/test/Fixtures/BoxRetentionPolicy/GetAllRetentionPolicies200.json, src/test/Fixtures/BoxRetentionPolicy/GetRetentionPolicyInfo200.json, src/test/Fixtures/BoxRetentionPolicy/UpdateRetentionPolicyInfo200.json, src/test/java/com/box/sdk/BoxRetentionPolicyAssignmentTest.java, src/test/java/com/box/sdk/BoxRetentionPolicyTest.java
=> feat: Add support for modifiable retention policies & enable deleting retention policy assignment

src/intTest/java/com/box/sdk/BoxRetentionPolicyAssignmentIT.java, src/intTest/java/com/box/sdk/MetadataIT.java, src/intTest/java/com/box/sdk/MetadataTemplateIT.java, src/main/java/com/box/sdk/BoxUser.java, src/main/java/com/box/sdk/CreateUserParams.java, src/main/java/com/box/sdk/internal/utils/JsonUtils.java, src/test/java/com/box/sdk/BoxUserTest.java
=> fix: Stop sending not specified optional fields when creating a user

src/main/java/com/box/sdk/BoxNotificationEmail.java, src/test/java/com/box/sdk/BoxUserTest.java
=> fix: Add missing constructor to `BoxNotificationEmail` class

src/intTest/java/com/box/sdk/BoxFileIT.java, src/intTest/java/com/box/sdk/BoxFolderIT.java, src/main/java/com/box/sdk/BoxFile.java, src/main/java/com/box/sdk/BoxFolder.java, src/test/Fixtures/BoxFile/GetFileInfo200.json, src/test/Fixtures/BoxFolder/GetFolderInfo200.json, src/test/java/com/box/sdk/BoxFileTest.java, src/test/java/com/box/sdk/BoxFolderTest.java
Closes: [SDK-2625](https://jira.inside-box.net/browse/SDK-2625)
=> feat: Add `is_accessible_via_shared_link` field to File and Folder

src/intTest/java/com/box/sdk/BoxWebHookIT.java, src/main/java/com/box/sdk/BoxWebHook.java
For now Webhooks can be created on file or folder. Later there will support Sign Requests
=> feat: Added Box Sign webhooks

build.gradle
build: Bumped `org.mockito:mockito-core:4.8.0`
build: Bumped `org.slf4j:slf4j-nop:2.0.3`
build: Bumped `com.puppycrawl.tools:checkstyle:9.3`
=> build: Bumped `org.bitbucket.b_c:jose4j:0.9.0`

src/main/java/com/box/sdk/BoxSignRequestPrefillTag.java, src/test/java/com/box/sdk/BoxSignRequestTest.java
=> fix: `NullPointerException` when using `BoxSignRequestPrefillTag`

README.md, doc/android.md
Added a guide explaining how to run the Java SDK in Android app with Kotling using interop.
=> docs: add android target guide

src/main/java/com/box/sdk/AbstractBoxMultipartRequest.java, src/main/java/com/box/sdk/RequestBodyFromCallback.java, src/main/java/com/box/sdk/RequestBodyFromStream.java, src/test/java/com/box/sdk/RequestBodyFromStreamTest.java
=> fix: Wrong progress reported to `ProgressListener` by `AbstractBoxMultipartRequest`

doc/users.md, src/intTest/java/com/box/sdk/BoxUserIT.java, src/main/java/com/box/sdk/BoxUser.java, src/test/java/com/box/sdk/BoxUserTest.java
=> feat: Add missing `fields` parameter to create and update `BoxUser` methods

src/main/java/com/box/sdk/BoxGroupMembership.java, src/test/java/com/box/sdk/BoxGroupMembershipTest.java
=> fix: Remove invalid Group membership role

src/main/java/com/box/sdk/SharedLinkAPIConnection.java, src/test/java/com/box/sdk/BoxItemTest.java
=> fix: `SharedLinkAPIConnection` uses request interceptor

src/main/java/com/box/sdk/BoxSearchParameters.java, src/test/java/com/box/sdk/BoxSearchParametersTest.java
=> feat: Support search deleted filters

README.md
=> chore: Add information about `BadPaddingException` to `README.md`

README.md, build.gradle
=> chore: Bumped `org.bitbucket.b_c:jose4j:0.9.4`

README.md, build.gradle, src/intTest/java/com/box/sdk/RetentionPolicyUtils.java
=> chore: Bumped com.squareup.okhttp3:okhttp:4.12.0

README.md, build.gradle, src/test/java/com/box/sdk/BoxDeveloperEditionAPIConnectionTest.java
=> feat: Bumped `org.bouncycastle:bcprov-jdk18on:1.77` and `org.bouncycastle:bcpkix-jdk18on:1.77`

src/main/java/com/box/sdk/BoxAPIConnection.java, src/main/java/com/box/sdk/BoxAPIRequest.java
=> fix: Fix `accessToken` locking mechanism

.github/workflows/build-and-test-daily.yml
=> chore: fix cron job notification
